### ISSUE TITLE
Add filter by origin to Filters Modal

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#12]
Depends on: https://github.com/kernelci/dashboard/issues/8

Include tree's origin field in the possible filter in Filters Modal.

Context: in https://github.com/kernelci/dashboard/issues/8 we merged multiple checkouts (each one with a different origin) into a single element.

**Comment by lfjnascimento** [comment]
We are using a origin selector on the Top bar now, so there is no need to add origin to Filters Modal
