### ISSUE TITLE
[Build details] Endpoint creation

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#15]

**Comment by lfjnascimento** [comment]
As discussed in the [slack thread](https://kernelci.slack.com/archives/C067UJC404A/p1721676102065819), we will:
- replace `Compiler string` and `Cross-compiler` by `builds.command`;
- and skip fields that are in design, but currently we do not have the data for them:
  - Config fragments
  - System
  - Machine Type
  - CPU
  - Release
  - Full release
