### ISSUE TITLE
[Boots tab] Validate all data is available

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#22]
https://www.figma.com/design/OY1Hp26cB4z3WyZPXxF8SE/KernelCI-Dashboard-V2?node-id=428-5765&t=HEYf8SJE55NTecHr-0

**Comment by WilsonNet** [comment]
One Build > Multiple Tests

Figma Configs -> Table Builds-> Column config

**Comment by WilsonNet** [comment]
Here the updated conversation

https://kernelci.slack.com/archives/C067UJC404A/p1722015822286389

**Comment by WilsonNet** [comment]
Closed on:
https://github.com/kernelci/dashboard/pull/60
