### ISSUE TITLE
Show issues card in the Build/Boot/Test Details Page AND Tree Details Page (all tabs)

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#28]
As requested here: https://kernelci.slack.com/archives/C067UJC404A/p1721387127725219?thread_ts=1721319407.397519&cid=C067UJC404A

We need to validate if all the required data is available ia if issues are related to builds and/or tests and show issues in the correct tab.
The initial idea is to show a list of issues that affect a particular commit. ~~So instead of showing a list of errors we would show a list of issues~~

Define what data is available in the Incidents/Issues so we can create the cards.

**Comment by joaobertacchi** [comment]
Waiting designs
