### ISSUE TITLE
Tree Details Page: each grouping of execution itens in the tests execution list

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#286]
**In Tests tab only**, show tree circles (Success, Failed, Inconclusive) for each grouping:
![Screenshot 2024-09-12 at 10 45 14](https://github.com/user-attachments/assets/f2b3dc9f-4bc7-41c6-a87b-9234b318c224)

Show exactly 3 circles.

**Colors**
- Success -> green
- Failed -> red
- Inconclusive -> grey

**Test Status Mapping**
- Success -> PASS
- Failed -> FAIL
- Inconclusive -> ERROR, MISS, SKIP, DONE, null

**Important**: when accordion is open, we show the correct test status for each test run! (keep it as it is now)

**Comment by lfjnascimento** [comment]
We also need to update the tests table on BuildDetailsPage with the same logic
