### ISSUE TITLE
Marcelo Onboarding

### ISSUE THREAD

**Issue by WilsonNet** [kernelci/dashboard#354]
https://github.com/kernelci/dashboard/blob/main/docs/Onboarding.md

- [x] Task 0: Check you proxy and Database access
- [x] Task 1: Run the Backend locally
- [x] Task 2: Get acquainted with the backend
- [x] Task 3: Get acquainted with the database
- [x] Task 4: Run the Frontend locally
- [x] Task 5: Complete a real Task

**Comment by MarceloRobert** [comment]
Query para obter os testes da tree de nome "android":
SELECT *
FROM tests AS t
INNER JOIN builds AS b ON t.build_id = b.id
INNER JOIN checkouts AS c ON b.checkout_id = c.id
WHERE c.tree_name = 'android'
