### ISSUE TITLE
Add virtualization for the tests table

### ISSUE THREAD

**Issue by WilsonNet** [kernelci/dashboard#371]
Some tests are too big and take too much time to open, add virtualization on them

![Image](https://github.com/user-attachments/assets/cd01320a-6d13-4aa2-93fd-afb8f77731e1)

Consider using 

https://tanstack.com/virtual/latest

**Comment by MarceloRobert** [comment]
Link for testing: https://dashboard.kernelci.org/tree/58e2d28ed28e5bc8836f8c14df1f94c27c1f9e2f?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22for-next%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Famlogic%2Flinux.git%22%2C%22treeName%22%3A%22amlogic%22%2C%22commitName%22%3A%22v6.12-rc1-18-g58e2d28ed28e5%22%2C%22headCommitHash%22%3A%2258e2d28ed28e5bc8836f8c14df1f94c27c1f9e2f%22%7D

**Comment by MarceloRobert** [comment]
Draft for this issue: https://github.com/kernelci/dashboard/pull/401

**Comment by WilsonNet** [comment]
moving to p0  because sorting gave it a performance hit for nesting tables
