### ISSUE TITLE
Bug: On the "Builds" tab, if I scroll down to the "Builds" table and click on any of the 4 builds, I can see tests were run there. However, the "Boots" and "Tests" tabs on top show "There is no boot/test data available for this tree"

### ISSUE THREAD

**Issue by WilsonNet** [kernelci/dashboard#378]
https://staging.dashboard.kernelci.org:9000/tree/1d227fcc72223cbdd34d0ce13541cbaab5e0d72f?tableFilter={%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22}&origin=maestro&currentTreeDetailsTab=treeDetails.builds&diffFilter={%22configs%22%3A{%22cros%3A%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-intel-pineview.flavour.config%22%3Atrue%2C%22cros%3A%2F%2Fchromeos-6.6%2Fx86_64%2Fchromeos-amd-stoneyridge.flavour.config%22%3Atrue%2C%22x86_64_defconfig%22%3Atrue}}&treeInfo={%22gitBranch%22%3A%22master%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Ftorvalds%2Flinux.git%22%2C%22treeName%22%3A%22mainline%22%2C%22commitName%22%3A%22v6.12-rc2-205-g1d227fcc7222%22%2C%22headCommitHash%22%3A%221d227fcc72223cbdd34d0ce13541cbaab5e0d72f%22}

On the "Builds" tab, if I scroll down to the "Builds" table and click on any of the 4 builds, I can see tests were run there. However, the "Boots" and "Tests" tabs on top show "There is no boot/test data available for this tree"

https://kernelci.slack.com/archives/C067UJC404A/p1728639801023089

**Comment by lfjnascimento** [comment]
My tests show that the problem here is that for some reason the mentioned link does not have any checkout selected (we can see this in the "Build History" graph), when we select a checkout, the Boots and Tests tabs work as they should
