### ISSUE TITLE
Make treeUrl editable in Drawer

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#38]
- The `treeUrl` is an editable link.
- The user can change the link and click on `Refresh`, in this case the page must use this information to fetch new data and update its UI

https://www.figma.com/design/OY1Hp26cB4z3WyZPXxF8SE/KernelCI-Dashboard-V2?node-id=505-3064&t=gx08d33QMO5uuKeG-4

**Comment by joaobertacchi** [comment]
For Tree Monitor we don't allow to change the tree/branch. For Devices/Labs tree can be deselected from a multioption selector. But user will never be able to change the tree url on the fly. Closing as invalid.
