### ISSUE TITLE
Tree Details Page: Add search field in Items Execution List

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#390]
- Remove pagination UI elements from the top of the table and add a search field instead.

![Screenshot 2024-10-14 at 11 54 03](https://github.com/user-attachments/assets/2241c9c0-d98b-48a1-8775-d626d73ad609)

**Comment by MarceloRobert** [comment]
Reference for search field using tanstack-table: https://tanstack.com/table/latest/docs/framework/react/examples/filters
