### ISSUE TITLE
Document an URL shortening proposal

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#396]
- Reduce URL size keeping it stable (for at least for 10 years)

**Comment by WilsonNet** [comment]
https://docs.google.com/document/d/1ChdHdPfbpOMjliE9wUXCZUsJkZR4YcONQOA0xqjTLFU/edit?tab=t.0

**Comment by WilsonNet** [comment]
Padovan approved here
https://discord.com/channels/1245820301053530313/1301896040349433957/1310970544136388608
