### ISSUE TITLE
Tests Tree filter isn't working properly when selecting multiples

### ISSUE THREAD

**Issue by Francisco2002** [kernelci/dashboard#423]
When applying a status filter in the tests tab, the return changes depending on the order of the filters

**How to test**

1. go to http://localhost:5173/tree/171aa289a6fe65faffeb92a1fda283c055435a62?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%22testStatus%22%3A%7B%22ERROR%22%3Atrue%2C%22SKIP%22%3Atrue%7D%7D&treeInfo=%7B%22gitBranch%22%3A%22for-next%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Famlogic%2Flinux.git%22%2C%22treeName%22%3A%22amlogic%22%2C%22commitName%22%3A%22v6.12-rc1-20-g171aa289a6fe%22%2C%22headCommitHash%22%3A%22171aa289a6fe65faffeb92a1fda283c055435a62%22%7D
2. go to http://localhost:5173/tree/171aa289a6fe65faffeb92a1fda283c055435a62?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=maestro&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%22testStatus%22%3A%7B%22ERROR%22%3Atrue%2C%22SKIP%22%3Atrue%7D%7D&treeInfo=%7B%22gitBranch%22%3A%22for-next%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Famlogic%2Flinux.git%22%2C%22treeName%22%3A%22amlogic%22%2C%22commitName%22%3A%22v6.12-rc1-20-g171aa289a6fe%22%2C%22headCommitHash%22%3A%22171aa289a6fe65faffeb92a1fda283c055435a62%22%7D
3. compare the results

**Comment by anajalvarenga** [comment]
Another error is to filtering data by test duration

**How to test**
1. Go to https://staging.dashboard.kernelci.org:9000/tree/e9001a382fa2c256229adc68d55212028b01d515?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22all%22%2C%22testsTable%22%3A%22all%22%7D&origin=redhat&currentTreeDetailsTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22master%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Fvirt%2Fkvm%2Fkvm.git%22%2C%22treeName%22%3A%22kvm%22%2C%22commitName%22%3A%22for-linus-30-ge9001a382fa2%22%2C%22headCommitHash%22%3A%22e9001a382fa2c256229adc68d55212028b01d515%22%7D

2. Try to apply a max and min test duration
