### ISSUE TITLE
[Bug] In Hardware list different entries show the same count (what is weird, invetigate)

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#525]
If you go to hardware llisting: https://dashboard.kernelci.org/hardware?origin=maestro
There are a lot of hardwares that will display the same results, investigate if they are necessary.

**Comment by WilsonNet** [comment]
According to nikolai is a natural cause of flat listing the hardware

Some generics board will have only one specific board, but the more test data we get the less probable that is to happen

**Comment by WilsonNet** [comment]
https://discord.com/channels/1245820301053530313/1301896040349433957/1314218238338535476
