### ISSUE TITLE
Test details: remove hardware/tree requirement to enter the page

### ISSUE THREAD

**Issue by MarceloRobert** [kernelci/dashboard#555]
Currently, you always need to access /tree/\<treeId\> or /hardware/\<hardwareId\> to acess /test/\<testId\>, it would be interesting to be able to go to a test details page directly, without passing through trees or hardwares

**Comment by joaobertacchi** [comment]
Keep old routes as redirects

**Comment by murilx** [comment]
When accessing a test via the link /test/$testId, no context is passed to the Test Details page, which is important when generating the Build Info link (to create the breadcrumb). As a result, a new route, /build/$buildId, must be created to address this issue. This route can handle cases where no context is provided, showing no breadcrumb when the context is missing.
