### ISSUE TITLE
defaults: Disable debug mode

### ISSUE THREAD

**Issue by pawiecz** [kernelci/dashboard#58]
Debug mode is enabled in the backend app even when `DEBUG` env is set to `False` (as in [docker-compose.yml:L46](https://github.com/kernelci/dashboard/blob/b1497b403b911320f1fd831677c7bbc175c9be3b/docker-compose.yml#L46C15-L46C26)).

It is caused by the [return value fallback branch when JSON cannot be decoded from given environmental variable](https://github.com/kernelci/dashboard/blob/b1497b403b911320f1fd831677c7bbc175c9be3b/backend/kernelCI/settings.py#L26).

In case of backend debug mode the returned value is `str("False")` instead of `bool(False)` which is a _truthy_ value:

```
$ docker-compose exec backend /bin/sh
/backend # source $(poetry env info -C ./backend --path)/bin/activate
(backend-py3.12) /backend # ./manage.py diffsettings --all | grep DEBUG
DEBUG = 'False'
### DEBUG_PROPAGATE_EXCEPTIONS = False
(backend-py3.12) /backend # python -c "print(bool('False'))"
True
```

This is why debug mode is always enabled.

I suggest switching default backend behaviour to disable debug mode and only make it optional for development environments. Also direct comparison of env value with expected string ("true", case insensitive) could be useful before casting it to Django setting value.

**Comment by WilsonNet** [comment]
This was handled in the linked `PR`, DEBUG is now `opt in`
