### ISSUE TITLE
[BUG] Builds is not being filtered by tests fields

### ISSUE THREAD

**Issue by lfjnascimento** [kernelci/dashboard#601]
We have global filters that are not affecting the builds because it is a separated endpoints that doesn't acknowledge hardware

This is for the treeDetails page, hardwareDetails is already a single endpoint but the global filters are on #618

**Comment by WilsonNet** [comment]
We are talking about global filters like hardware

**Comment by MarceloRobert** [comment]
Since this issue originally was talking about the commitGraph but was changed to the treeDetails page in general, there is a new issue for the commitGraph in specific: #640
