### ISSUE TITLE
More obvious highlighting of full log download

### ISSUE THREAD

**Issue by broonie** [kernelci/dashboard#624]
Speaking to another kernel developer offline he mentioned that he'd not noticed that there was a full log download available as well as the excerpts. TBH I can see the issue he was having - the "Logs" box isn't super highlighted, the excerpt is in a larger font with stronger colours and the link for the log is truncated. It'd be good to do something to highlight the fact that there's a full log available.

**Comment by MarceloRobert** [comment]
Solved in [PR 670](https://github.com/kernelci/dashboard/pull/670)
