### ISSUE TITLE
Filter Tests by Path in Hardware Details is not properly working

### ISSUE THREAD

**Issue by Francisco2002** [kernelci/dashboard#629]
When we try to filter a test by path in hardware details, the result is empty. But it has correspondence in the listing.

| Listing | Filter |
| --------- | ------ |
| ![Image](https://github.com/user-attachments/assets/8dadf6c2-3d68-4dbb-9798-e0ffcfc32370) | ![Image](https://github.com/user-attachments/assets/46756cca-de96-4b47-b52e-1476c7b75bac) |

**Comment by murilx** [comment]
This issue, from November 29 seems to be working in the current state of the application. Here's the evidence

*Testing the filter from commit 099f6e569857e6b810e2dc0ac74f37e4c7061c37 (the last commit of November 29)*
![Image](https://github.com/user-attachments/assets/4c285326-7ae9-4b35-825b-e2be1f99bd9c)
![Image](https://github.com/user-attachments/assets/72715364-1d2c-4c7c-96ad-7aac62f8fc5e)

*Testing the filter from commit 14be4af76d7a3de39561495d402a04e2b60096bf (the last commit in main during this test)*
![Image](https://github.com/user-attachments/assets/7553d2f0-81b0-4957-a1e0-b73a90d1168a)
![Image](https://github.com/user-attachments/assets/ff84119e-b954-4aa6-a50f-44b61ff43ebd)
