### ISSUE TITLE
Filtering tests by issue

### ISSUE THREAD

**Issue by broonie** [kernelci/dashboard#631]
When an issue is reported in the issues box it is very difficult to go from that to the test run that failed. For example, with 

https://dashboard.kernelci.org/tree/3106ac6516bafc19c903de63d95b05e149802f7a?tableFilter=%7B%22buildsTable%22%3A%22all%22%2C%22bootsTable%22%3A%22failed%22%2C%22testsTable%22%3A%22failed%22%7D&origin=maestro&currentPageTab=treeDetails.tests&diffFilter=%7B%7D&treeInfo=%7B%22gitBranch%22%3A%22linus-next%22%2C%22gitUrl%22%3A%22https%3A%2F%2Fgit.kernel.org%2Fpub%2Fscm%2Flinux%2Fkernel%2Fgit%2Fsashal%2Flinus-next.git%22%2C%22treeName%22%3A%22sashal-next%22%2C%22commitName%22%3A%22v6.12-12007-g3106ac6516baf%22%2C%22headCommitHash%22%3A%223106ac6516bafc19c903de63d95b05e149802f7a%22%7D&intervalInDays=7

there are two warnings in regulator_unregister() but clicking on that (or anything else in the issues list) doesn't do anything - I would have expected that this would do something like filter things down to runs showing the reported issue.

**Comment by MarceloRobert** [comment]
Solved in [PR 648](https://github.com/kernelci/dashboard/pull/648) and [PR 669](https://github.com/kernelci/dashboard/pull/669)
