### ISSUE TITLE
Hardware: address feedback from Kevin (email)

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#652]
Helen Mae Koike Fornazier
8:46 AM (1 hour ago)
to Kevin, Gustavo, me

Hi Kevin,

Thank you for your feedback, we'll analize it and incorporate into the Web dashboard development.

(cc +João)

---- On Thu, 05 Dec 2024 20:58:30 -0300 Kevin Hilman  wrote ---

 > Hi Helen,
 > 
 > 
 > Helen Mae Koike Fornazier helen.koike@collabora.com> writes:
 > 
 > > We now have a page to track errors per hardware in our staging instance.
 > >
 > > For Amlogic: https://staging.dashboard.kernelci.org:9000/hardware?origin=maestro&intervalInDays=3&hardwareSearch=amlogic
 > >
 > > It would be great to get your feedback on this.
 > >
 > 
 > Thanks for reaching out.  I gave it a quick spin, but TL;DR; it is not
 > very intuitive.
 > 
 > I tried a few things, but for initial feedback, I'll just give you a
 > walk through of one of the things I tried to try to understand a single
 > boot failure:
 > 
 > - on the "amlogic,meson-gxl" line, I see 2 boot failures.  So I click on
 >  that red 2, (my expectation: see boot results for that SoC)
 > 
 > - on that page, I see results for that SoC, but the default tab is for
 >  build results (I clicked on boot results)
 > 
 > - Next to the Builds tab, I see a Boots tab which shows 4 failures
 >  (remember the initial summary page showed 2)
 > 
 > - I click on the Boots tab, which has a red 4, and I see
 >  Issues: 1 (in red)
 >  Unknown: 4 (in grey)
 > 
 >  -ECONFUSED   What are "Issues?"

Issue is a object that can group several results.

For instance, if we identify the same errors happens in 5 results, we can put all
the results in the same issue.
We are doing this grouping based on regex, this is a recent adition, we are still
improving this tool.

Regards,
Helen

 > 
 > - looking further into the table below, the default view of that table
 >  is showing "All", but I came to this page looking for failures.
 > 
 >  UX issue: the selection above betwwen Build / Boot / Tests looks like
 >  tabs, but here the selection beween All / Success / Failed /
 >  Inconclusive looks different, and it's not immedately obvious that you
 >  can click those and it will change the filter.  That shoudl probably
 >  be tabs like the build/boot/tests selection
 > 
 > - So then,  on to the "Failed" tab-thats-not-a-tab :)  Here I see this
 >  is 4, which matches the Boots tab above (but again, doesn't match the
 >  2 that showed on the initial summary page.)
 > 
 > - Next, in the list of failed boots, I click the first one, which takes
 >  to a page which shows me all the info about the arch/logs/urls etc.,
 >  and the main thing I notice is that it reports "No Issues".  Again,
 >  what are "issues?"
 > 
 >  I also noticed that the kernel branch is linux-4.19.y, which I'm
 >  suprised by because I don't remember seeing that old of kernel in the
 >  list of trees on the initial page.  Going back, I see there are
 >  a ton of trees in the initial list (most of which I don't care about.)
 > 
 >  But on this page, I can't tell what tree this is since it only shows
 >  the "Git Repository URL" which is truncated.  I have to hover on it to
 >  see it's stable-rc repo.
 > 
 > - Moving on, I came here knowhing there was a failure somewhere, so I
 >  click on the logs link, and finally I see the boot log and indeed the
 >  kernel doesn't boot.
 > 
 > - But even here, while I know what SoC this is (amlogic,meson-gxl) I
 >  have no idea what *board* this is.
 > 
 >  The early part of the boot log is truncated so I can't see the early
 >  boot.  I can only decipher the board by looking in detail at the
 >  bootlog to see which DTB the bootloader is TFTP'ing.
 > 
 > Anyways, that's probably enough for now.
 > 
 > I hope that's helpful for some initial feedback, but I think there's
 > lots of things here that are not user-friendly defaults.
 > 
 > > We are going to have a meeting with the Webdashboard developers on
 > > Monday at 9:00 AM (UTC-3) via this
 > > link https://meet.google.com/tsz-geot-ibs (hmm, maybe it is too early
 > > for you) , it would be wonderful if you could participate and share
 > > your thoughts.
 > 
 > Yes, definitely too early for me (I'm UTC-8).
 > 
 > Kevin

**Comment by MarceloRobert** [comment]
> on the "amlogic,meson-gxl" line, I see 2 boot failures. So I click on
> that red 2, (my expectation: see boot results for that SoC)
> 
> on that page, I see results for that SoC, but the default tab is for
> build results (I clicked on boot results)
We have an issue for this: #523 

> Next to the Builds tab, I see a Boots tab which shows 4 failures
> (remember the initial summary page showed 2)
We have an issue and are working on this: #577

**Comment by MarceloRobert** [comment]
> But on this page, I can't tell what tree this is since it only shows
the "Git Repository URL" which is truncated. I have to hover on it to
see it's stable-rc repo.

- [ ] #674 

>  > But even here, while I know what SoC this is (amlogic,meson-gxl) I
    have no idea what board this is.
>
> The early part of the boot log is truncated so I can't see the early
boot. I can only decipher the board by looking in detail at the
bootlog to see which DTB the bootloader is TFTP'ing.

- [ ] #678

**Comment by MarceloRobert** [comment]
The issues from this feedback were addressed as linked in the comments above
