### ISSUE TITLE
Build Details Page: remove 'kernel image', 'dtb', 'modules', and bring info from the discussion

### ISSUE THREAD

**Issue by joaobertacchi** [kernelci/dashboard#653]
This was discussed in Discord, instead of showing unstable fields that are a JSON in the Database, we get those json and iterate over to show all those values, being key as the title and value as the displayed value

**Comment by MarceloRobert** [comment]
Follows [this discord message](https://discord.com/channels/1245820301053530313/1245820301053530316/1310608051006472356)
