### ISSUE TITLE
Drop trees configuration and show all trees in Trees Listing Page

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#8]
Merge multiple checkouts by commit. And display them as a single tree.
Notice that checkouts are CI system dependent, so multiple checkouts can refer to the same commit. By merging them we show data from multiple CI systems in a single view. Each CI system is identified by the origin field.

**Comment by lfjnascimento** [comment]
As discussed in the [Slack Thread](https://kernelci.slack.com/archives/C067UJC404A/p1722607060195589?thread_ts=1722355781.145189&cid=C067UJC404A), we will use the concept of `revision` instead of `tree`
