### ISSUE TITLE
Epic 4: Tree Details Page with functional Tests tab and Links Structure

### ISSUE THREAD

**Issue by bdilly** [kernelci/dashboard#87]
**Sprint Goal:** navigate to any Tree Details pages in Tree Listing page (the client will pick one during demo). In Tests tab, User select specific tests and see test details. User can share details (links structure task). User can also navigate using navbar (origin selection)

**Comment by joaobertacchi** [comment]
stable-rc/branch => a single instance

Helen:
- health status of the tree => history graph
